//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_cre_credential
    {
        public int cre_codcredential { get; set; }
        public string cre_projectid { get; set; }
        public string cre_token { get; set; }
        public string cre_domain { get; set; }
        public string cre_phone { get; set; }
        public string cre_status { get; set; }
        public string cre_insertuser { get; set; }
        public Nullable<System.DateTime> cre_insertdate { get; set; }
        public string cre_insertterminal { get; set; }
        public string cre_updateuser { get; set; }
        public Nullable<System.DateTime> cre_updatedate { get; set; }
        public string cre_updateterminal { get; set; }
    }
}
