//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_mes_message
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tm_mes_message()
        {
            this.tm_sen_sent = new HashSet<tm_sen_sent>();
        }
    
        public int mes_codmessage { get; set; }
        public Nullable<System.DateTime> mes_created { get; set; }
        public string mes_to { get; set; }
        public string mes_message { get; set; }
        public string mes_status { get; set; }
        public string mes_insertuser { get; set; }
        public Nullable<System.DateTime> mes_insertdate { get; set; }
        public string mes_insertterminal { get; set; }
        public string mes_updateuser { get; set; }
        public Nullable<System.DateTime> mes_updatedate { get; set; }
        public string mes_updateterminal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tm_sen_sent> tm_sen_sent { get; set; }
    }
}
