//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_sen_sent
    {
        public int sen_codsent { get; set; }
        public Nullable<int> sen_codmessage { get; set; }
        public Nullable<System.DateTime> sen_sent { get; set; }
        public string sen_twiliocode { get; set; }
        public string sen_status { get; set; }
        public string sen_insertuser { get; set; }
        public Nullable<System.DateTime> sen_insertdate { get; set; }
        public string sen_insertterminal { get; set; }
        public string sen_updateuser { get; set; }
        public Nullable<System.DateTime> sen_updatedate { get; set; }
        public string sen_updateterminal { get; set; }
    
        public virtual tm_mes_message tm_mes_message { get; set; }
    }
}
